version: '3.7'
services:
  launcher-js-server:
    container_name: launcher-js-server
    build: ./server
    networks:
      - demo
    env_file:
      - .env
  launcher-js-client:
    container_name: launcher-js-client
    build: ./client
    networks:
      - demo
    depends_on:
      - launcher-js-server
    env_file:
      - .env
    environment:
      - TARGET_URL=http://launcher-js-server:8080/ping
networks:
  demo:
