receivers:
    opencensus:
      endpoint: "0.0.0.0:55678"
    otlp:
      protocols:
          grpc:
  
exporters:
    prometheus:
        endpoint: "0.0.0.0:8889"

    logging:
        loglevel: debug

    # when a satellite with OTLP configured is available
    # otlp:
    #   endpoint: satellite:8360
    #   insecure: true

    # configuring otlp to public satellites
    otlp:
      endpoint: ingest.lightstep.com:443
      headers: {"lightstep-access-token":<TOKEN HERE>}

    # lightstep:
    #     access_token: <TOKEN HERE>
    #     satellite_host: "ingest.lightstep.com"
    #     satellite_port: 443
    #     service_name: "myService"
    #     plain_text: false
  
processors:
    batch:
    queued_retry:
  
service:
    pipelines:
      traces:
        receivers: [opencensus, otlp]
        # when a satellite with OTLP configured is available
        exporters: [logging, otlp]
        # exporters: [logging, lightstep]
        processors: [batch]
      metrics:
        receivers: [opencensus, otlp]
        exporters: [logging]